apiVersion: v1
kind: Service
metadata:
  name: php-app-blue
spec:
  selector:
    app: php-app
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort

