apiVersion: v1
kind: Service
metadata:
  name: php-app-green
spec:
  selector:
    app: php-app
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort

